name: jahs

channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scikit-learn
  - tqdm
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - seaborn=0.12
  - matplotlib=3.5.2
  - pip
  - pip:
      - torchsummary
      - smac
      - configspace
